version: '2'
services:
    pictrip-app:
        image: pictrip
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pictrip-postgresql:5432/pictrip
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=pictrip-elasticsearch:9300
        ports:
            - 8080:8080
    pictrip-postgresql:
        extends:
            file: postgresql.yml
            service: pictrip-postgresql
    pictrip-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: pictrip-elasticsearch
